<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260221095604 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE model_export DROP CONSTRAINT fk_616b320b166d1f9c');
        $this->addSql('DROP TABLE model_export');
        $this->addSql('ALTER TABLE project DROP created_at');
        $this->addSql('ALTER TABLE project DROP updated_at');
        $this->addSql('ALTER TABLE project DROP status');
        $this->addSql('ALTER TABLE project DROP input_data');
        $this->addSql('ALTER TABLE project DROP result_data');
        $this->addSql('ALTER TABLE project DROP calculated_at');
        $this->addSql('ALTER TABLE project DROP excel_path');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE model_export (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(32) NOT NULL, filename VARCHAR(255) DEFAULT NULL, download_path VARCHAR(255) DEFAULT NULL, error_message TEXT DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_616b320b166d1f9c ON model_export (project_id)');
        $this->addSql('ALTER TABLE model_export ADD CONSTRAINT fk_616b320b166d1f9c FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE project ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE project ADD status VARCHAR(32) DEFAULT \'draft\' NOT NULL');
        $this->addSql('ALTER TABLE project ADD input_data JSON DEFAULT \'{}\' NOT NULL');
        $this->addSql('ALTER TABLE project ADD result_data JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD calculated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD excel_path VARCHAR(255) DEFAULT NULL');
    }
}
